### ISSUE TITLE
Atom crashes immediately after entering anything into any .asm file.

### ISSUE THREAD

**Issue by davidkowalk** [nicholatian/language-armasm#3]
Using version 2.0.3

As soon as you enter any character into a .asm file atom immediately freezes and then crashes.

Idk, seems pretty serious to me. Kinda makes the package unusable.

**Comment by nicholatian** [comment]
I’m gonna attempt reproduction and then fix this later tonight. I’ll do some testing to make sure it works, but when I publish it, feedback to make sure it’s resolved on your end would be greatly appreciated too.

**Comment by nicholatian** [comment]
Unfortunately I have been unable to reproduce this bug. A new setup of Atom with this language grammar lets me type ARM assembly just fine. Your bug lies elsewhere upstream.
